name: Export Signed iOS Archive
description: Export a signed iOS Archive

inputs:
  export_options:
    description: |
      The file containing the export options to use 
      for signing the archive.
    required: true
  output_artifact_ref:
    description: |
      The reference ID / name of the uploaded GitHub artifact
      stored in GitHub by the upload action.
    required: true

runs:
  using: composite
  steps:
    - name: Sign & Export
      env:
        EXPORT_OPTIONS: ${{ inputs.export_options }}
      shell: bash
      run: |
        xcodebuild \
        -exportArchive \
        -archivePath AriesBifold.xcarchive \
        -exportPath export \
        -exportOptionsPlist ./$EXPORT_OPTIONS \
        -verbose

    - name: Upload signed artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact_ref }}.ipa
        path: export/BCWallet.ipa
        if-no-files-found: error
        retention-days: 7
