name: Ship to SauceLabs
description: Upload an artifact to saucelabs

inputs:
  sauce_labs_username:
    description: SauceLabs username
    required: true
  sauce_labs_password:
    description: SauceLabs password
    required: true
  sauce_labs_name:
    description: |
      The name of the artifact shown in SauceLabs
    required: true
  sauce_labs_description:
    description: |
      The description of the artifact show in SauceLabs.
    required: true
  artifact_ref:
    description: |
      The referene ID / name of the uploaded GitHub artifact
      stored in GitHub by the upload action. i.e my-artifact
    required: true
  artifact_name:
    description: |
      The actual name of the artifact that would be
      recognized by a human i.e MyApp.ipa
    required: true

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_ref }}

    - name: Set tags based on context
      id: set_tags
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          TAGS="pr,pr-${{ github.event.pull_request.number }}"
        elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
          TAGS="rc"
        else
          TAGS=""
        fi
        echo "tags=$TAGS" >> $GITHUB_OUTPUT

    - name: Upload artifact to SauceLabs
      shell: bash
      env:
        SAUCE_USERNAME: ${{ inputs.sauce_labs_username }}
        SAUCE_ACCESS_KEY: ${{ inputs.sauce_labs_password }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        SAUCE_LABS_NAME: ${{ inputs.sauce_labs_name }}
        SAUCE_LABS_DESCRIPTION: ${{ inputs.sauce_labs_description }}
        TAGS: ${{ steps.set_tags.outputs.tags }}
      run: |
        TAG_ARGS=""
        if [ -n "$TAGS" ]; then
          IFS=',' read -ra TAG_ARRAY <<< "$TAGS"
          for tag in "${TAG_ARRAY[@]}"; do
            TAG_ARGS="$TAG_ARGS --form tags=$tag"
          done
        fi

        curl \
        -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" \
        -X POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
        --form "payload=@$ARTIFACT_NAME" \
        --form "name=$SAUCE_LABS_NAME" \
        --form "description=$SAUCE_LABS_DESCRIPTION" \
        $TAG_ARGS